import React, { createContext, useContext, useState } from 'react';

const LangContext = createContext(null);

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    newBooking: 'New Booking',
    allBookings: 'All Bookings',
    dispatch: 'Dispatch',
    tankerAssignment: 'Tanker Assignment',
    driverManagement: 'Driver Management',
    maintenance: 'Maintenance',
    routeOptimizer: 'Route Optimizer',
    dpScheduler: 'DP Scheduler',
    slotAllocator: 'Slot Allocator',
    flowOptimizer: 'Flow Optimizer',
    waterQuality: 'Water Quality',
    payments: 'Payments',
    analytics: 'Analytics',
    operations: 'OPERATIONS',
    fleet: 'FLEET',
    algorithms: 'ALGORITHMS (DAA)',
    qualityFinance: 'QUALITY & FINANCE',

    // Dashboard
    welcomeBack: 'Welcome back',
    systemOnline: 'System Online',
    totalBookings: 'Total Bookings',
    pending: 'Pending',
    activeDispatches: 'Active Dispatches',
    todayRevenue: 'Today Revenue',
    driversAvailable: 'Drivers Available',
    maintenanceDue: 'Maintenance Due',
    revenueTrend: 'Revenue Trend',
    weeklyRevenue: 'Weekly revenue overview',
    fleetStatus: 'Fleet Status',
    tankerAvailability: 'Tanker availability',
    available: 'Available',
    enRoute: 'En Route',
    loading: 'Loading',
    maintenanceStatus: 'Maintenance',
    recentBookings: 'Recent Bookings',
    latestOrders: 'Latest customer orders',
    viewAll: 'View All →',
    quickActions: 'Quick Actions',
    createOrder: 'Create water delivery order',
    assignTanker: 'Assign tanker to booking',
    findRoute: 'Find shortest delivery path',
    addDriver: 'Register new driver',
    newBookingAction: 'New Booking',
    dispatchTanker: 'Dispatch Tanker',
    routeOpt: 'Route Optimizer',
    waterQualityTitle: 'Water Quality',
    passRate: 'Pass Rate',
    driverPerformance: 'Driver Performance',
    systemCoverage: 'System Coverage',
    areas: 'Areas',
    sources: 'Sources',
    tankers: 'Tankers',
    deliveries: 'Deliveries',
    areaCoverage: 'Area Coverage',

    // Login
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    phone: 'Phone',
    enterEmail: 'Enter your email',
    enterPassword: 'Enter your password',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    createAccount: 'Create Account',
    registering: 'Creating account...',
    signingIn: 'Signing in...',
    backToHome: 'Back to home',
    demoAccess: 'Demo Access',
    tryDemo: 'Try with demo credentials',
    clickRole: 'Click any role below to auto-fill and sign in instantly.',
    quickLogin: 'Quick Login',
    adminRole: 'Full Access',
    dispatcherRole: 'Dispatch & Bookings',
    driverRole: 'My Deliveries',
    customerRole: 'Book Water',

    // Landing
    smartWater: 'Smart Water',
    tankerManagement: 'Tanker',
    forPakistan: 'for Pakistan',
    landingSubtitle: "Real-time fleet tracking, intelligent booking, WHO-compliant water quality monitoring, and automated dispatch — all in one platform.",
    startFreeTrial: 'Start Free Trial',
    bookWater: 'Book water',
    seeHowItWorks: 'See How It Works',
    activeOperators: 'Active Operators',
    litresDay: 'Litres/Day',
    ontimeDelivery: 'On-time Delivery',
    powerfulFeatures: 'Powerful Features',
    everythingYouNeed: 'Everything you need to run a modern tanker fleet',
    nineModules: 'Nine integrated modules designed specifically for Pakistani water distribution.',
    fleetTracking: 'Real-Time Fleet Tracking',
    fleetTrackingDesc: 'Track every tanker on an interactive map. GPS-based ETAs, geofenced delivery zones.',
    qualityLab: 'WHO-Compliant Quality Lab',
    qualityLabDesc: 'Log pH, TDS, turbidity, chlorine tests. Automatic pass/fail grading.',
    smsAlerts: 'SMS & WhatsApp Alerts',
    smsAlertsDesc: 'Customers receive SMS when tanker dispatches, arrives, and delivers.',
    paymentIntegration: 'JazzCash + EasyPaisa',
    paymentIntegrationDesc: 'Native Pakistani payment integration. Accept cash, bank transfer, JazzCash, EasyPaisa.',
    businessIntelligence: 'Business Intelligence',
    businessIntelligenceDesc: '9 dashboards, 24 KPIs, revenue forecasting, customer LTV.',
    predictiveMaintenance: 'Predictive Maintenance',
    predictiveMaintenanceDesc: 'Track oil changes, tires, brakes. Auto-alerts when service is due.',
    driverManagementFeature: 'Driver Management',
    driverManagementDesc: 'CNIC, license, medical expiry tracking. Performance ratings.',
    fuelAnalytics: 'Fuel Analytics',
    fuelAnalyticsDesc: 'Per-tanker fuel consumption, mileage tracking, cost-per-km analysis.',
    bankSecurity: 'Bank-Grade Security',
    bankSecurityDesc: 'PDO prepared statements, CSRF protection, role-based access.',
    howItWorks: 'How It Works',
    fourSteps: 'From booking to delivery in four steps',
    customerBooks: 'Customer Books',
    customerBooksDesc: 'Customer places order via phone, WhatsApp, or web portal.',
    dispatchAssigns: 'Dispatch Assigns',
    dispatchAssignsDesc: 'Dispatcher assigns nearest available tanker + driver.',
    liveTracking: 'Live Tracking',
    liveTrackingDesc: 'Driver tracks route on GPS. Customer sees live location.',
    deliveryPayment: 'Delivery & Payment',
    deliveryPaymentDesc: 'Water delivered, customer confirms. Payment collected.',
    coverage: 'Pakistan Coverage',
    activeCities: 'Active in 9 major cities',
    pricing: 'Pricing',
    starterPlan: 'Starter',
    professionalPlan: 'Professional',
    enterprisePlan: 'Enterprise',
    month: '/mo',
    getStarted: 'Get Started',
    contactUs: 'Contact Us',
    readyToModernize: 'Ready to modernize your tanker fleet?',

    // Common
    search: 'Search...',
    filter: 'Filter',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',
    confirm: 'Confirm',
    actions: 'Actions',
    status: 'Status',
    date: 'Date',
    amount: 'Amount',
    id: 'ID',
    name: 'Name',
    type: 'Type',
    customer: 'Customer',
    area: 'Area',
    time: 'Time',
    details: 'Details',
    overview: 'Overview',
    bookings: 'Bookings',
    fleet: 'Fleet',
    quality: 'Quality',
    finance: 'Finance',
    revenue: 'Revenue',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    outstanding: 'Outstanding',
    transactions: 'Transactions',
    totalTests: 'Total Tests',
    passed: 'Passed',
    failed: 'Failed',
    avgScore: 'Avg Score',
    totalRevenue: 'Total Revenue',
    totalCollected: 'Total Collected',
    cash: 'Cash',
    jazzcash: 'JazzCash',
    easypaisa: 'EasyPaisa',
    bankTransfer: 'Bank Transfer',
    revenueByMethod: 'Revenue by Method',
    paymentHistory: 'Payment History',
    bookingDetails: 'Booking Details',
    bookingStatus: 'Booking Status Distribution',
    allBookingsTitle: 'All Bookings',
    newBookingBtn: 'New Booking',
    totalTankers: 'Total Tankers',
    loadingStatus: 'Loading',
    maintenanceAlerts: 'Maintenance Alerts',
    overdue: 'OVERDUE',
    allUpToDate: 'All maintenance up to date',
    whoStandards: 'WHO Standards',
    qualityTestResults: 'Quality Test Results',
    pHLevel: 'pH Level',
    tds: 'TDS',
    turbidity: 'Turbidity',
    chlorine: 'Chlorine',
    bacteria: 'Bacteria',
    absent: 'Absent',
    welcomeTo: 'Welcome to',
    loginToContinue: 'Sign in to your account to continue',
    invalidCredentials: 'Invalid email or password',
    passwordsNoMatch: 'Passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters',
    emailAlreadyRegistered: 'Email already registered',
    joinToBook: 'Join AquaManager to book water tankers',
    register: 'Register',
    login: 'Login',
    logout: 'Logout',
    profile: 'Profile',
    settings: 'Settings',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    urdu: 'اردو',
    english: 'English',
    // More
    truckerFleet: 'Tanker Fleet',
    fuel: 'Fuel',
    trips: 'trips',
    onTime: 'on-time',
    rating: 'rating',
    overdueAlert: 'Due:',
    current: 'Current',
    totalDelivered: 'Total Delivered',
    capacity: 'Capacity',
    score: 'Score',
    testedBy: 'Tested By',
    lastService: 'Last Service',
    nextService: 'Next Service',
    cost: 'Cost',
    notes: 'Notes',
    summary: 'Summary',
    weeklyRev: 'Weekly revenue overview',
    toggleSidebar: 'Toggle sidebar',
    dAaProject: 'DAA Semester Project',
    karachiWater: 'Karachi Water Distribution',
    back: '← Back',
    welcome: 'Welcome',
    smartDashboard: 'Smart Dashboard',
    dark: 'Dark',
    light: 'Light',
  },

  ur: {
    // Navigation
    dashboard: 'ڈیش بورڈ',
    newBooking: 'نئی بکنگ',
    allBookings: 'تمام بکنگز',
    dispatch: 'ڈسپیچ',
    tankerAssignment: 'ٹینکر تفویض',
    driverManagement: 'ڈرائیور مینجمنٹ',
    maintenance: 'دیکھ بھال',
    routeOptimizer: 'راستہ بہتر',
    dpScheduler: 'DP شیڈولر',
    slotAllocator: 'สล็อٹ مختص',
    flowOptimizer: 'فلو بہتر',
    waterQuality: 'پانی کا معیار',
    payments: 'ادائیگیاں',
    analytics: 'تجزیات',
    operations: 'آپریشنز',
    fleet: 'بیڑا',
    algorithms: 'الگورتھم (DAA)',
    qualityFinance: 'معیار اور مالیات',

    // Dashboard
    welcomeBack: 'خوش آمدید',
    systemOnline: 'سسٹم آن لائن',
    totalBookings: 'کل بکنگز',
    pending: 'زیر التوا',
    activeDispatches: 'فعال ڈسپیچ',
    todayRevenue: 'آج کی آمدنی',
    driversAvailable: 'دستیاب ڈرائیور',
    maintenanceDue: 'دیکھ بھال ضروری',
    revenueTrend: 'آمدنی کا رجحان',
    weeklyRevenue: 'ہفتہ وار آمدنی',
    fleetStatus: 'بیڑے کی صورتحال',
    tankerAvailability: 'ٹینکر دستیابی',
    available: 'دستیاب',
    enRoute: 'راستے میں',
    loading: 'لوڈ ہو رہا ہے',
    maintenanceStatus: 'دیکھ بھال',
    recentBookings: 'حالیہ بکنگز',
    latestOrders: 'تازہ ترین گاہک آرڈرز',
    viewAll: 'سب دیکھیں →',
    quickActions: 'فوری اقدامات',
    createOrder: 'پانی کی ڈلیوری کا آرڈر بنائیں',
    assignTanker: 'ٹینکر مختص کریں',
    findRoute: 'مختصر ترین راستہ تلاش کریں',
    addDriver: 'نیا ڈرائیور رجسٹر کریں',
    newBookingAction: 'نئی بکنگ',
    dispatchTanker: 'ٹینکر بھیجیں',
    routeOpt: 'راستہ بہتر',
    waterQualityTitle: 'پانی کا معیار',
    passRate: 'پاس شرح',
    driverPerformance: 'ڈرائیور کارکردگی',
    systemCoverage: 'سسٹم کوریج',
    areas: 'علاقے',
    sources: 'ذرائع',
    tankers: 'ٹینکرز',
    deliveries: 'ڈلیوریز',
    areaCoverage: 'علاقائی کوریج',

    // Login
    signIn: 'لاگ ان',
    signUp: 'سائن اپ',
    email: 'ای میل',
    password: 'پاس ورڈ',
    confirmPassword: 'پاس ورڈ دہرائیں',
    fullName: 'پورا نام',
    phone: 'فون',
    enterEmail: 'اپنا ای میل درج کریں',
    enterPassword: 'اپنا پاس ورڈ درج کریں',
    forgotPassword: 'پاس ورڈ بھول گئے؟',
    noAccount: 'اکاؤنٹ نہیں ہے؟',
    hasAccount: 'پہلے سے اکاؤنٹ ہے؟',
    createAccount: 'اکاؤنٹ بنائیں',
    registering: 'اکاؤنٹ بن رہا ہے...',
    signingIn: 'لاگ ان ہو رہا ہے...',
    backToHome: 'ہوم پیج پر واپس',
    demoAccess: 'ڈیمو تک رسائی',
    tryDemo: 'ڈیمو کریڈنشلز کے ساتھ آزمائیں',
    clickRole: 'نیچے کوئی بھی رول کلک کریں فوری لاگ ان کے لیے۔',
    quickLogin: 'فوری لاگ ان',
    adminRole: 'مکمل رسائی',
    dispatcherRole: 'ڈسپیچ اور بکنگز',
    driverRole: 'میری ڈلیوریز',
    customerRole: 'پانی بک کریں',

    // Landing
    smartWater: 'سمارٹ پانی',
    tankerManagement: 'ٹینکر مینجمنٹ',
    forPakistan: 'پاکستان کے لیے',
    landingSubtitle: 'ریئل ٹائم فلیٹ ٹریکنگ، ذہین بکنگ، WHO مطابق پانی کے معیار کی نگرانی، اور خودکار ڈسپیچ۔',
    startFreeTrial: 'مفت ٹرائل شروع کریں',
    bookWater: 'پانی بک کریں',
    seeHowItWorks: 'دیکھیں کیسے کام کرتا ہے',
    activeOperators: 'فعال آپریٹرز',
    litresDay: 'لیٹر/دن',
    ontimeDelivery: 'وقت پر ڈلیوری',
    powerfulFeatures: 'طاقتور خصوصیات',
    everythingYouNeed: 'آپ کے جدید ٹینکر فلیٹ کو چلانے کے لیے سب کچھ',
    nineModules: 'پاکستانی پانی کی تقسیم کے لیے خصوصی نو ماڈیولز۔',
    fleetTracking: 'ریئل ٹائم فلیٹ ٹریکنگ',
    fleetTrackingDesc: 'ہر ٹینکر کو انٹرایکٹیو میپ پر ٹریک کریں۔ GPS ETA، ڈلیوری زونز۔',
    qualityLab: 'WHO مطابق کوالٹی لیب',
    qualityLabDesc: 'pH، TDS، ٹربیڈیٹی، کلورین ٹیسٹ۔ خودکار پاس/فال گریڈنگ۔',
    smsAlerts: 'ایس ایم ایس اور واٹس ایپ الارٹس',
    smsAlertsDesc: 'گاہک کو ایس ایم ایس ملتی ہے جب ٹینکر بھیجا جاتا ہے، پہنچتا ہے، اور ڈلیور کرتا ہے۔',
    paymentIntegration: 'جیز کیش اور ایزی پیسہ',
    paymentIntegrationDesc: 'مقامی پاکستانی ادائیگی انٹیگریشن۔ کیش، بینک ٹرانسفر قبول کریں۔',
    businessIntelligence: 'کاروباری انٹیلیجنس',
    businessIntelligenceDesc: '9 ڈیش بورڈز، 24 KPIs، آمدنی کی پیش گوئی۔',
    predictiveMaintenance: 'پیش گوئی دیکھ بھال',
    predictiveMaintenanceDesc: 'تیل، ٹائر، بریکس ٹریک کریں۔ خودکار الارٹس۔',
    driverManagementFeature: 'ڈرائیور مینجمنٹ',
    driverManagementDesc: 'CNIC، لائسنس، طبی ختم ہونے کی نگرانی۔ کارکردگی۔',
    fuelAnalytics: 'ایندھن کی تجزیات',
    fuelAnalyticsDesc: 'فی ٹینکر ایندھن کا استعمال، مائیلیج ٹریکنگ۔',
    bankSecurity: 'بینک گریڈ سیکیورٹی',
    bankSecurityDesc: 'PDO، CSRF حفاظت، رول بیسڈ رسائی۔',
    howItWorks: 'کیسے کام کرتا ہے',
    fourSteps: 'بکنگ سے ڈلیوری تک چار قدم',
    customerBooks: 'گاہک بک کرتا ہے',
    customerBooksDesc: 'گاہک فون، واٹس ایپ، یا ویب پورٹل پر آرڈر دیتا ہے۔',
    dispatchAssigns: 'ڈسپیچ مختص کرتا ہے',
    dispatchAssignsDesc: 'ڈسپچر قریب ترین دستیاب ٹینکر + ڈرائیور مختص کرتا ہے۔',
    liveTracking: 'لائیو ٹریکنگ',
    liveTrackingDesc: 'ڈرائیور GPS پر راستہ ٹریک کرتا ہے۔ گاہک لائیو لوکیشن دیکھتا ہے۔',
    deliveryPayment: 'ڈلیوری اور ادائیگی',
    deliveryPaymentDesc: 'پانی ڈلیور ہوا، گاہک تصدیق کرتا ہے۔ ادائیگی وصول ہوتی ہے۔',
    coverage: 'پاکستان کوریج',
    activeCities: '9 بڑے شہروں میں فعال',
    pricing: 'قیمتیں',
    starterPlan: 'شروعاتی',
    professionalPlan: 'پیشہ ورانہ',
    enterprisePlan: 'انٹرپرائز',
    month: '/ماہ',
    getStarted: 'شروع کریں',
    contactUs: 'رابطہ کریں',
    readyToModernize: 'اپنے ٹینکر فلیٹ کو جدید بنانے کے لیے تیار ہیں؟',

    // Common
    search: 'تلاش کریں...',
    filter: 'فلٹر',
    save: 'محفوظ کریں',
    cancel: 'منسوخ',
    delete: 'حذف',
    edit: 'ترمیم',
    add: 'شامل کریں',
    close: 'بند کریں',
    confirm: 'تصدیق',
    actions: 'اقدامات',
    status: 'حالت',
    date: 'تاریخ',
    amount: 'رقم',
    id: 'آئی ڈی',
    name: 'نام',
    type: 'قسم',
    customer: 'گاہک',
    area: 'علاقہ',
    time: 'وقت',
    details: 'تفصیلات',
    overview: 'جائزہ',
    bookings: 'بکنگز',
    fleet: 'بیڑا',
    quality: 'معیار',
    finance: 'مالیات',
    revenue: 'آمدنی',
    today: 'آج',
    thisWeek: 'اس ہفتے',
    thisMonth: 'اس مہینے',
    outstanding: 'باقی',
    transactions: 'لین دین',
    totalTests: 'کل ٹیسٹ',
    passed: 'کامیاب',
    failed: 'ناکام',
    avgScore: 'اوسط اسکور',
    totalRevenue: 'کل آمدنی',
    totalCollected: 'کل وصول شدہ',
    cash: 'کیش',
    jazzcash: 'جیز کیش',
    easypaisa: 'ایزی پیسہ',
    bankTransfer: 'بینک ٹرانسفر',
    revenueByMethod: 'طریقے سے آمدنی',
    paymentHistory: 'ادائیگی کی تاریخ',
    bookingDetails: 'بکنگ کی تفصیلات',
    bookingStatus: 'بکنگ کی حالت کی تقسیم',
    allBookingsTitle: 'تمام بکنگز',
    newBookingBtn: 'نئی بکنگ',
    totalTankers: 'کل ٹینکرز',
    loadingStatus: 'لوڈ ہو رہا ہے',
    maintenanceAlerts: 'دیکھ بھال الارٹس',
    overdue: 'ورن ہو گیا',
    allUpToDate: 'تمام دیکھ بھال کا وقت ہے',
    whoStandards: 'WHO معیارات',
    qualityTestResults: 'کوالٹی ٹیسٹ کے نتائج',
    pHLevel: 'pH لیول',
    tds: 'TDS',
    turbidity: 'ٹربیڈیٹی',
    chlorine: 'کلورین',
    bacteria: 'بیکٹیریا',
    absent: 'موجود نہیں',
    welcomeTo: 'خوش آمدید',
    loginToContinue: 'اکاؤنٹ میں لاگ ان کریں',
    invalidCredentials: 'غلط ای میل یا پاس ورڈ',
    passwordsNoMatch: 'پاس ورڈ مماثل نہیں',
    passwordMinLength: 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے',
    emailAlreadyRegistered: 'ای میل پہلے سے رجسٹرڈ ہے',
    joinToBook: 'پانی ٹینکر بک کرنے کے لیے AquaManager میں شامل ہوں',
    register: 'رجسٹر',
    login: 'لاگ ان',
    logout: 'لاگ آؤٹ',
    profile: 'پروفائل',
    settings: 'ترتیبات',
    language: 'زبان',
    theme: 'تھیم',
    darkMode: 'ڈارک موڈ',
    lightMode: 'لائٹ موڈ',
    urdu: 'اردو',
    english: 'English',
    // More
    truckerFleet: 'ٹینکر فلیٹ',
    fuel: 'ایندھن',
    trips: 'سفر',
    onTime: 'وقت پر',
    rating: 'درجہ بندی',
    overdueAlert: 'وقت:',
    current: 'موجودہ',
    totalDelivered: 'کل ڈلیور شدہ',
    capacity: 'صعت',
    score: 'اسکور',
    testedBy: 'ٹیسٹ کیا',
    lastService: 'آخری سروس',
    nextService: 'اگلی سروس',
    cost: 'لاگت',
    notes: 'نوٹس',
    summary: 'خلاصہ',
    weeklyRev: 'ہفتہ وار آمدنی',
    toggleSidebar: 'سائیڈ بار ٹوگل',
    dAaProject: 'DAA سیمیسٹر پروجیکٹ',
    karachiWater: 'کراچی پانی تقسیم',
    back: '← واپس',
    welcome: 'خوش آمدید',
    smartDashboard: 'سمارٹ ڈیش بورڈ',
    dark: 'ڈارک',
    light: 'لائٹ',
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try {
      const saved = localStorage.getItem('aqua_lang');
      if (saved === 'ur' || saved === 'en') return saved;
    } catch(e) {}
    return 'en';
  });

  const toggleLang = () => {
    setLang(prev => {
      const next = prev === 'en' ? 'ur' : 'en';
      localStorage.setItem('aqua_lang', next);
      return next;
    });
  };

  const t = (key) => translations[lang][key] || key;

  return (
    <LangContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
}
